# Generated by Django 4.0.4 on 2022-10-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='useroradminregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=240, null=True)),
                ('lastname', models.CharField(max_length=240, null=True)),
                ('email', models.EmailField(max_length=240, null=True)),
                ('username', models.CharField(max_length=240, null=True)),
                ('password', models.CharField(max_length=240, null=True)),
            ],
        ),
    ]
