# Generated by Django 4.0.4 on 2022-10-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PeojectApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='useroradminregistration',
            new_name='registration',
        ),
    ]
