# Generated by Django 4.0.4 on 2022-10-21 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PeojectApp', '0003_registration_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='password',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='username',
        ),
    ]
