# Generated by Django 4.0.4 on 2022-10-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeojectApp', '0004_remove_registration_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VehicleNumber', models.CharField(max_length=255)),
                ('VehicleModel', models.CharField(max_length=255)),
                ('VehicleType', models.CharField(max_length=255)),
                ('VehicleDescription', models.CharField(max_length=400)),
            ],
        ),
    ]
