# Generated by Django 4.0.4 on 2022-10-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeojectApp', '0005_vehicleregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desigination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desigination', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
