# Generated by Django 4.0.4 on 2022-10-21 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PeojectApp', '0006_desigination'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='desigination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PeojectApp.desigination'),
        ),
    ]
